create table brands
(
    id         bigint generated by default as identity (start with 1000 increment by 1),
    name       varchar(255) not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table categories
(
    id         bigint generated by default as identity (start with 1000 increment by 1),
    name       varchar(255) not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table products
(
    id          bigint generated by default as identity (start with 1000 increment by 1),
    name        varchar(255) not null,
    price       numeric(38, 2) not null,
    brand_id    bigint not null,
    category_id bigint not null,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    primary key (id)
);